### ISSUE TITLE
Standards home?

### ISSUE THREAD

**Issue by annevk** [whatwg/compression#32]
Will this become part of Streams or do we create a new "top-level" compression standard somewhere?

**Comment by ricea** [comment]
I have a mild preference for keeping it standalone, since in my mind it is a separate entity.

However, adding it into Streams would certainly be the shortest route to standardisation.

**Comment by domenic** [comment]
It might be time to consider this more seriously now that this is shipping in both Chrome and Safari.

**Comment by annevk** [comment]
Keeping it standalone seems reasonable. Not sure if it neatly fits into the scope of an existing Workstream. Probably worth asking the WHATWG SG for advice?

**Comment by yoavweiss** [comment]
I'm happy to try and get it adopted at WebPerfWG, if that works.

**Comment by marcoscaceres** [comment]
Ok, cool. It's good to have options... for WebPerfWG, it would require a recharter, right? I wonder if going through the WHATWG might be less bureaucratic... 🤔

**Comment by yoavweiss** [comment]
We're in the middle of a rechartering, so I don't think this is an issue. For WHATWG, are you thinking of creating a work stream for it?

**Comment by marcoscaceres** [comment]
I would guess so (just going from what @annevk said above) - I'm not at all familiar with the WHATWG process for setting up a work stream, but I believe either Anne and Domenic should be. 

@CanonMukai, @ricea, @domenic, would be great to hear your preferences and opinions about venue.

**Comment by ricea** [comment]
Thanks @marcoscaceres. I don't have a particular preference, so whichever way is less overhead is best. This spec doesn't require much attention, so any overhead is likely to form a large part of the work.

**Comment by saschanaz** [comment]
This is now implemented in all three browser engines 🎉

If this goes to WebPerfWG, does it mean the official inclusion will happen after 2023-08-31 per the end date of the current extension in https://www.w3.org/2021/02/webperf.html ?

**Comment by yoavweiss** [comment]
> If this goes to WebPerfWG, does it mean the official inclusion will happen after 2023-08-31 per the end date of the current extension in https://www.w3.org/2021/02/webperf.html ?

Yeah, that would be the easiest.

**Comment by marcoscaceres** [comment]
I tend to agree with @smaug---- (and @annevk), as the WHATWG being the place where streams seem to live... and I guess also why I was looking to get @domenic's input too.   

@yoavweiss, any objections to just letting the WHATWG take it? Easiness aside, it seems like the logical home for it or is there some strong incentive to move it to WebPerf?

**Comment by yoavweiss** [comment]
If WHATWG is interested in creating a workstream for it, and @ricea is on board, I have no objections. (In that case, I would just ask for ricea@ to update the WG on future work, as the WG has a lot of interested consumers of this API, that can provide useful feedback IMO)

**Comment by saschanaz** [comment]
Has there been some progress over this? This is staying here way too long given the implementation status, is there something we can help from our side?

**Comment by cwilso** [comment]
@yoavweiss Thoughts?

**Comment by yoavweiss** [comment]
As I said previously, I'd be happy to bring adoption to the WebPerfWG for discussion, but there seemed to be some desire for WHATWG adoption, at least at the time. Has that not materialized?

**Comment by saschanaz** [comment]
https://github.com/whatwg/sg/issues/231 will discuss about this.

**Comment by annevk** [comment]
I think this can be considered done. #59 and https://github.com/whatwg/sg/issues/231 track the remainder. Thanks everyone!
